package edu.weijunyong.satedgesim.server;

import java.util.LinkedHashMap;
import java.util.Map;

public class ExecutionReceipt {
    public boolean accepted = false;
    public boolean actionAccepted = false;
    public boolean executionScheduled = false;
    public boolean taskCompleted = false;
    public boolean taskSucceeded = false;
    public long decisionId = -1L;
    public long taskId = -1L;
    public int policyUpperAction = -1;
    public String policyUpperActionName = "";
    public int selectedVmIndex = -1;
    public long selectedVmId = -1L;
    public String selectedVmLogicalTier = "";
    public int selectedVmAbstractAction = -1;
    public int executedVmIndex = -1;
    public long executedVmId = -1L;
    public String executedLogicalTier = "";
    public int executedAbstractAction = -1;
    public boolean intentExecutionMatch = false;
    public String fallbackReason = "none";
    public double delay = 0.0;
    public double energyRawCounterBefore = 0.0;
    public double energyRawCounterAfter = 0.0;
    public double energyDelta = 0.0;
    /**
     * Backward-compatibility field.
     * In server mode this now mirrors taskSucceeded (not actionAccepted).
     */
    public boolean success = false;
    public String failureReason = "none";
    public boolean deadlineMiss = false;
    public boolean queueOverflow = false;
    public boolean vmUnavailable = false;
    public boolean linkUnavailable = false;
    public boolean taskDropped = false;
    public boolean invalidAction = false;
    public boolean simulationFailure = false;
    public boolean latencyExceeded = false;
    public boolean resourceExceeded = false;
    public boolean unknownFailure = false;
    public double deadline = 0.0;
    public int queueLength = 0;
    public double estimatedTotalDelaySec = 0.0;
    public double estimatedQueueLength = 0.0;
    public double estimatedTransmissionRateMbps = 0.0;
    public double estimatedComputeCapacity = 0.0;
    public boolean linkAvailableNow = false;
    public double estimatedLinkLifetimeSec = 0.0;
    public double estimatedTaskTransmissionTimeSec = 0.0;
    public double estimatedTaskComputeTimeSec = 0.0;
    public double estimatedTaskCompletionTimeSec = 0.0;
    public double linkSurvivalMarginSec = 0.0;
    public double linkSurvivalMarginToCompletionSec = 0.0;
    public boolean handoverRequired = false;
    public boolean handoverAvailable = false;
    public double mobilityRisk = 1.0;
    public String mobilityRiskSource = "unavailable";
    public double serverProcessingMs = 0.0;
    public String scenarioProfile = "default";
    public String taskSourceMode = "current";
    public String successProfile = "default";
    public String message = "";

    public Map<String, Object> toMap() {
        Map<String, Object> out = new LinkedHashMap<String, Object>();
        out.put("accepted", accepted);
        out.put("actionAccepted", actionAccepted);
        out.put("executionScheduled", executionScheduled);
        out.put("taskCompleted", taskCompleted);
        out.put("taskSucceeded", taskSucceeded);
        out.put("decisionId", decisionId);
        out.put("taskId", taskId);
        out.put("policyUpperAction", policyUpperAction);
        out.put("policyUpperActionName", policyUpperActionName);
        out.put("selectedVmIndex", selectedVmIndex);
        out.put("selectedVmId", selectedVmId);
        out.put("selectedVmLogicalTier", selectedVmLogicalTier);
        out.put("selectedVmAbstractAction", selectedVmAbstractAction);
        out.put("executedVmIndex", executedVmIndex);
        out.put("executedVmId", executedVmId);
        out.put("executedLogicalTier", executedLogicalTier);
        out.put("executedAbstractAction", executedAbstractAction);
        out.put("intentExecutionMatch", intentExecutionMatch);
        out.put("fallbackReason", fallbackReason);
        out.put("delay", delay);
        out.put("energyRawCounterBefore", energyRawCounterBefore);
        out.put("energyRawCounterAfter", energyRawCounterAfter);
        out.put("energyDelta", energyDelta);
        out.put("success", success);
        out.put("failureReason", failureReason);
        out.put("deadlineMiss", deadlineMiss);
        out.put("queueOverflow", queueOverflow);
        out.put("vmUnavailable", vmUnavailable);
        out.put("linkUnavailable", linkUnavailable);
        out.put("taskDropped", taskDropped);
        out.put("invalidAction", invalidAction);
        out.put("simulationFailure", simulationFailure);
        out.put("latencyExceeded", latencyExceeded);
        out.put("resourceExceeded", resourceExceeded);
        out.put("unknownFailure", unknownFailure);
        out.put("deadline", deadline);
        out.put("queueLength", queueLength);
        out.put("estimatedTotalDelaySec", estimatedTotalDelaySec);
        out.put("estimatedQueueLength", estimatedQueueLength);
        out.put("estimatedTransmissionRateMbps", estimatedTransmissionRateMbps);
        out.put("estimatedComputeCapacity", estimatedComputeCapacity);
        out.put("linkAvailableNow", linkAvailableNow);
        out.put("estimatedLinkLifetimeSec", estimatedLinkLifetimeSec);
        out.put("estimatedTaskTransmissionTimeSec", estimatedTaskTransmissionTimeSec);
        out.put("estimatedTaskComputeTimeSec", estimatedTaskComputeTimeSec);
        out.put("estimatedTaskCompletionTimeSec", estimatedTaskCompletionTimeSec);
        out.put("linkSurvivalMarginSec", linkSurvivalMarginSec);
        out.put("linkSurvivalMarginToCompletionSec", linkSurvivalMarginToCompletionSec);
        out.put("handoverRequired", handoverRequired);
        out.put("handoverAvailable", handoverAvailable);
        out.put("mobilityRisk", mobilityRisk);
        out.put("mobilityRiskSource", mobilityRiskSource);
        out.put("serverProcessingMs", serverProcessingMs);
        out.put("scenarioProfile", scenarioProfile);
        out.put("taskSourceMode", taskSourceMode);
        out.put("successProfile", successProfile);
        out.put("message", message);
        return out;
    }
}
