package edu.weijunyong.satedgesim.server;

import java.util.LinkedHashMap;
import java.util.Map;

public class ExecutionReceipt {
    public String receiptStage = "scheduling";
    public boolean accepted = false;
    public boolean actionAccepted = false;
    public boolean executionScheduled = false;
    public Boolean taskCompleted = null;
    public Boolean taskSucceeded = null;
    public long decisionId = -1L;
    public long taskId = -1L;
    public double simulationTime = 0.0;
    public int policyUpperAction = -1;
    public String policyUpperActionName = "";
    public int selectedVmIndex = -1;
    public long selectedVmId = -1L;
    public String selectedVmLogicalTier = "";
    public int selectedVmAbstractAction = -1;
    public int executedVmIndex = -1;
    public long executedVmId = -1L;
    public String executedLogicalTier = "";
    public int executedAbstractAction = -1;
    public boolean intentExecutionMatch = false;
    public String fallbackReason = "none";
    public double delay = 0.0;
    public Double energyRawCounterBefore = null;
    public Double energyRawCounterAfter = null;
    public Double energyDelta = null;
    public Double receiptEnergyBeforeWh = null;
    public Double receiptEnergyAfterWh = null;
    public Double receiptEnergyDeltaWh = null;
    public String energySource = "receipt_delta_wh";
    public String energyUnit = "Wh";
    public boolean energySourceAvailable = false;
    public String energyUnavailableReason = "energy_counter_not_read";
    public RlResourceProfile resourceProfile = RlResourceProfile.fromAction(null, RlResourceBindingMode.candidate_only);
    public String continuousResourceBindingMode = "candidate_only";
    public boolean continuousResourceApplied = false;
    public boolean nativeSchedulerBound = false;
    public boolean estimatorBound = false;
    public boolean fullHybridClosedLoopClaimAllowed = false;
    public boolean nativeBindingApplied = false;
    public boolean nativeCpuMipsBound = false;
    public boolean nativeNetworkBandwidthBound = false;
    public boolean nativeTxPowerBound = false;
    public double nativeBaseMips = 0.0;
    public double nativeAppliedMips = 0.0;
    public double nativeCpuShare = 1.0;
    public double nativeBandwidthShare = 1.0;
    public double nativeTxPowerRatio = 1.0;
    public String nativeCpuBindingScope = RlNativeResourceBindingSemantics.CPU_BINDING_SCOPE;
    public String nativeNetworkBindingScope = RlNativeResourceBindingSemantics.NETWORK_BINDING_SCOPE;
    public String nativeTxPowerBindingScope = RlNativeResourceBindingSemantics.TX_POWER_BINDING_SCOPE;
    public Map<String, Object> nativeBinding = null;
    public double estimatorExpectedDelaySec = 0.0;
    public double estimatorExpectedEnergyJ = 0.0;
    public double estimatorEffectiveMips = 0.0;
    public double estimatorEffectiveBandwidthMbps = 0.0;
    public double estimatorTxPowerW = 0.0;
    /**
     * Backward-compatibility field.
     * In server mode this now mirrors taskSucceeded (not actionAccepted).
     */
    public Boolean success = null;
    public String failureReason = "none";
    public boolean deadlineMiss = false;
    public boolean queueOverflow = false;
    public boolean vmUnavailable = false;
    public boolean linkUnavailable = false;
    public boolean taskDropped = false;
    public boolean invalidAction = false;
    public boolean simulationFailure = false;
    public boolean latencyExceeded = false;
    public boolean resourceExceeded = false;
    public boolean unknownFailure = false;
    public double deadline = 0.0;
    public int queueLength = 0;
    public double estimatedTotalDelaySec = 0.0;
    public double estimatedQueueLength = 0.0;
    public double estimatedTransmissionRateMbps = 0.0;
    public double estimatedComputeCapacity = 0.0;
    public boolean linkAvailableNow = false;
    public double estimatedLinkLifetimeSec = 0.0;
    public double estimatedTaskTransmissionTimeSec = 0.0;
    public double estimatedTaskComputeTimeSec = 0.0;
    public double estimatedTaskCompletionTimeSec = 0.0;
    public double linkSurvivalMarginSec = 0.0;
    public double linkSurvivalMarginToCompletionSec = 0.0;
    public boolean handoverRequired = false;
    public boolean handoverAvailable = false;
    public double mobilityRisk = 1.0;
    public String mobilityRiskSource = "unavailable";
    public double serverProcessingMs = 0.0;
    public String scenarioProfile = "default";
    public String taskSourceMode = "current";
    public String successProfile = "default";
    public String message = "";

    public Map<String, Object> toMap() {
        Map<String, Object> out = new LinkedHashMap<String, Object>();
        out.put("receiptStage", receiptStage);
        out.put("accepted", accepted);
        out.put("actionAccepted", actionAccepted);
        out.put("executionScheduled", executionScheduled);
        out.put("taskCompleted", taskCompleted);
        out.put("taskSucceeded", taskSucceeded);
        out.put("decisionId", decisionId);
        out.put("taskId", taskId);
        out.put("simulationTime", simulationTime);
        out.put("policyUpperAction", policyUpperAction);
        out.put("policyUpperActionName", policyUpperActionName);
        out.put("selectedVmIndex", selectedVmIndex);
        out.put("selectedVmId", selectedVmId);
        out.put("selectedVmLogicalTier", selectedVmLogicalTier);
        out.put("selectedVmAbstractAction", selectedVmAbstractAction);
        out.put("executedVmIndex", executedVmIndex);
        out.put("executedVmId", executedVmId);
        out.put("executedLogicalTier", executedLogicalTier);
        out.put("executedAbstractAction", executedAbstractAction);
        out.put("intentExecutionMatch", intentExecutionMatch);
        out.put("fallbackReason", fallbackReason);
        out.put("delay", delay);
        out.put("energyRawCounterBefore", energyRawCounterBefore);
        out.put("energyRawCounterAfter", energyRawCounterAfter);
        out.put("energyDelta", energyDelta);
        out.put("receipt_energy_before_wh", receiptEnergyBeforeWh);
        out.put("receipt_energy_after_wh", receiptEnergyAfterWh);
        out.put("receipt_energy_delta_wh", receiptEnergyDeltaWh);
        out.put("energySource", energySource);
        out.put("energyUnit", energyUnit);
        out.put("energySourceAvailable", energySourceAvailable);
        out.put("energy_source_available", energySourceAvailable);
        out.put("energyUnavailableReason", energyUnavailableReason);
        out.put("energy_unavailable_reason", energyUnavailableReason);
        out.put("resourceProfile", resourceProfile == null ? null : resourceProfile.toMap());
        out.put("continuousResourceBindingMode", continuousResourceBindingMode);
        out.put("continuous_resource_binding_mode", continuousResourceBindingMode);
        out.put("continuousResourceApplied", continuousResourceApplied);
        out.put("continuous_resource_applied", continuousResourceApplied);
        out.put("nativeSchedulerBound", nativeSchedulerBound);
        out.put("native_scheduler_bound", nativeSchedulerBound);
        out.put("estimatorBound", estimatorBound);
        out.put("estimator_bound", estimatorBound);
        out.put("fullHybridClosedLoopClaimAllowed", fullHybridClosedLoopClaimAllowed);
        out.put("full_hybrid_closed_loop_claim_allowed", fullHybridClosedLoopClaimAllowed);
        out.put("nativeBindingApplied", nativeBindingApplied);
        out.put("native_binding_applied", nativeBindingApplied);
        out.put("nativeCpuMipsBound", nativeCpuMipsBound);
        out.put("native_cpu_mips_bound", nativeCpuMipsBound);
        out.put("nativeNetworkBandwidthBound", nativeNetworkBandwidthBound);
        out.put("native_network_bandwidth_bound", nativeNetworkBandwidthBound);
        out.put("nativeTxPowerBound", nativeTxPowerBound);
        out.put("native_tx_power_bound", nativeTxPowerBound);
        out.put("nativeBaseMips", nativeBaseMips);
        out.put("native_base_mips", nativeBaseMips);
        out.put("nativeAppliedMips", nativeAppliedMips);
        out.put("native_applied_mips", nativeAppliedMips);
        out.put("nativeCpuShare", nativeCpuShare);
        out.put("native_cpu_share", nativeCpuShare);
        out.put("nativeBandwidthShare", nativeBandwidthShare);
        out.put("native_bandwidth_share", nativeBandwidthShare);
        out.put("nativeTxPowerRatio", nativeTxPowerRatio);
        out.put("native_tx_power_ratio", nativeTxPowerRatio);
        out.put("nativeCpuBindingScope", nativeCpuBindingScope);
        out.put("native_cpu_binding_scope", nativeCpuBindingScope);
        out.put("nativeNetworkBindingScope", nativeNetworkBindingScope);
        out.put("native_network_binding_scope", nativeNetworkBindingScope);
        out.put("nativeTxPowerBindingScope", nativeTxPowerBindingScope);
        out.put("native_tx_power_binding_scope", nativeTxPowerBindingScope);
        out.put("nativeBinding", nativeBinding);
        out.put("native_binding", nativeBinding);
        out.put("estimatorExpectedDelaySec", estimatorExpectedDelaySec);
        out.put("estimatorExpectedEnergyJ", estimatorExpectedEnergyJ);
        out.put("estimatorEffectiveMips", estimatorEffectiveMips);
        out.put("estimatorEffectiveBandwidthMbps", estimatorEffectiveBandwidthMbps);
        out.put("estimatorTxPowerW", estimatorTxPowerW);
        out.put("success", success);
        out.put("failureReason", failureReason);
        out.put("deadlineMiss", deadlineMiss);
        out.put("queueOverflow", queueOverflow);
        out.put("vmUnavailable", vmUnavailable);
        out.put("linkUnavailable", linkUnavailable);
        out.put("taskDropped", taskDropped);
        out.put("invalidAction", invalidAction);
        out.put("simulationFailure", simulationFailure);
        out.put("latencyExceeded", latencyExceeded);
        out.put("resourceExceeded", resourceExceeded);
        out.put("unknownFailure", unknownFailure);
        out.put("deadline", deadline);
        out.put("queueLength", queueLength);
        out.put("estimatedTotalDelaySec", estimatedTotalDelaySec);
        out.put("estimatedQueueLength", estimatedQueueLength);
        out.put("estimatedTransmissionRateMbps", estimatedTransmissionRateMbps);
        out.put("estimatedComputeCapacity", estimatedComputeCapacity);
        out.put("linkAvailableNow", linkAvailableNow);
        out.put("estimatedLinkLifetimeSec", estimatedLinkLifetimeSec);
        out.put("estimatedTaskTransmissionTimeSec", estimatedTaskTransmissionTimeSec);
        out.put("estimatedTaskComputeTimeSec", estimatedTaskComputeTimeSec);
        out.put("estimatedTaskCompletionTimeSec", estimatedTaskCompletionTimeSec);
        out.put("linkSurvivalMarginSec", linkSurvivalMarginSec);
        out.put("linkSurvivalMarginToCompletionSec", linkSurvivalMarginToCompletionSec);
        out.put("handoverRequired", handoverRequired);
        out.put("handoverAvailable", handoverAvailable);
        out.put("mobilityRisk", mobilityRisk);
        out.put("mobilityRiskSource", mobilityRiskSource);
        out.put("serverProcessingMs", serverProcessingMs);
        out.put("scenarioProfile", scenarioProfile);
        out.put("taskSourceMode", taskSourceMode);
        out.put("successProfile", successProfile);
        out.put("message", message);
        return out;
    }
}
